on:
  push:
    branches: [ main ]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Renovate
        run: npm install -g renovate
      - name: Run Renovate
        run: renovate --token ${{ secrets.GITHUB_TOKEN }}
